#!/bin/sh
sqlplus64 "user/pass@(DESCRIPTION=(ADDRESS=(PROTOCOL=TCP)(Host=oracle.cs.torontomu.ca)(Port=1521))(CONNECT_DATA=(SID=orcl)))" <<EOF
COMMIT;
DROP TABLE waitlist CASCADE CONSTRAINTS;
DROP TABLE borrows CASCADE CONSTRAINTS;
DROP TABLE reviews CASCADE CONSTRAINTS;
DROP TABLE game_copies CASCADE CONSTRAINTS;
DROP TABLE game_genres CASCADE CONSTRAINTS;
DROP TABLE games CASCADE CONSTRAINTS;
DROP TABLE genres CASCADE CONSTRAINTS;
DROP TABLE age_rating_ref CASCADE CONSTRAINTS;
DROP TABLE users CASCADE CONSTRAINTS;
DROP TABLE admins CASCADE CONSTRAINTS;
exit;
EOF